name: guessheritage
description: A Flutter quiz about world cultural heritage
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  just_audio: ^0.9.39
  audio_session: ^0.1.18
  # (valfritt) förbättrad nätbild-cache – kommentera bort om du inte vill
  cached_network_image: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/data/questions.json
    - assets/icons/   # pyramid.png + pyramid_fg.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/icons/pyramid.png
  adaptive_icon_foreground: assets/icons/pyramid_fg.png
  adaptive_icon_background: "#FFFFFF"
  remove_alpha_ios: true
