name: guess_the_heritage
description: A heritage quiz game.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Lokaliseringsstöd
  flutter_localizations:
    sdk: flutter

  # Spara språkval lokalt
  shared_preferences: ^2.2.3

  # Bakgrundsmusik
  just_audio: ^0.9.40

  # (om/när du använder http)
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - assets/data/questions.json
    - assets/audio/FloridaBirds.mp3
    - assets/icons/

# Korrekt nyckel (den gamla "flutter_icons" är deprecated)
flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/icons/pyramid.png
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: assets/icons/pyramid_fg.png
  min_sdk_android: 21
