name: guess_heritage
description: A heritage quiz game.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Lokaliseringsstöd från Flutter
  flutter_localizations:
    sdk: flutter

  # Spara språkval lokalt
  shared_preferences: ^2.2.3

  # Bakgrundsmusik (du har redan en mp3)
  just_audio: ^0.9.40

  # (valfritt om du använder http i andra delar)
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.2

flutter:
  uses-material-design: true

  assets:
    - assets/data/questions.json
    - assets/audio/FloridaBirds.mp3
    - assets/icons/
