name: guess_the_heritage
description: A soothing heritage quiz with global coverage and ambiance music.
publish_to: 'none'
version: 0.1.1+2

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  just_audio: ^0.9.39
  audio_session: ^0.1.18

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/
    - assets/data/questions.json

flutter pub get
