name: Fill Commons images

on:
  workflow_dispatch: {}

# GITHUB_TOKEN får push-rättigheter
permissions:
  contents: write

jobs:
  fill:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (with token)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install requests

      - name: Run filler
        run: python tool/fill_commons_images.py

      # Pusha tillbaka ändrad questions.json
      - name: Auto-commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(data): fill Commons images + attributions"
          file_pattern: assets/data/questions.json
          branch: ${{ github.ref_name }}
