name: Flutter Android (recreate android folder)

on:
  push:
    branches: [ main ]
    paths:
      - 'lib/**'
      - 'assets/**'
      - 'pubspec.yaml'
      - '.github/workflows/flutter-android.yml'
  pull_request:

concurrency:
  group: android-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable 3.22.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      # Skapa om android/ så den alltid är modern
      - name: Recreate android/ and write valid AndroidManifest.xml
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.kalleboo --project-name guessheritage
          cat > android/app/src/main/AndroidManifest.xml <<'XML'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <uses-permission android:name="android.permission.INTERNET"/>
              <application
                  android:label="guessheritage"
                  android:name="${applicationName}"
                  android:icon="@mipmap/ic_launcher">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
                  <meta-data
                      android:name="io.flutter.embedding.android.NormalTheme"
                      android:resource="@style/NormalTheme"/>
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2"/>
              </application>
          </manifest>
          XML

      # 🔧 GENERERA APP-IKONERNA (motsvarar "dart run flutter_launcher_icons")
      - name: Generate launcher icons
        run: dart run flutter_launcher_icons

      - name: Analyze
        run: flutter analyze

      # Bygg både debug & release
      - name: Build APKs
        run: |
          flutter build apk --debug --target=lib/main.dart
          flutter build apk --release --target=lib/main.dart

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
