name: Flutter Android APK
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Create Android project
        run: flutter create . --platforms=android

      - name: List root
        run: ls -la

      - name: List lib
        run: ls -la lib || true

      - name: List assets
        run: ls -la assets || true

      - name: List assets/data
        run: ls -la assets/data || true

      - name: Show pubspec
        run: sed -n '1,200p' pubspec.yaml

      - name: Flutter pub get
        run: flutter pub get

      - name: Install Android NDK 27
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;27.0.12077973"

      - name: Patch ndkVersion (Kotlin DSL)
        run: |
          if [ -f android/app/build.gradle.kts ]; then
            grep -q 'ndkVersion' android/app/build.gradle.kts || sed -i '0,/android\s*{/{s//android {\n    ndkVersion = "27.0.12077973"/}' android/app/build.gradle.kts
          fi

      - name: Patch ndkVersion (Groovy)
        run: |
          if [ -f android/app/build.gradle ]; then
            grep -q 'ndkVersion' android/app/build.gradle || sed -i '0,/android\s*{/{s//android {\n    ndkVersion "27.0.12077973"/}' android/app/build.gradle
          fi

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Build release APK
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
