name: Flutter Android APK
on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Show Flutter version
        run: flutter --version

      # Skapar bara Android-mappen — kan råka lägga in demo-filer i lib/
      - name: Create Android project (android folder only)
        run: flutter create . --platforms=android

      # Återställ vår egen lib/ efter flutter create så demot inte ersätter koden
      - name: Restore our lib after create
        run: |
          git checkout -- lib || true
          test -f lib/main.dart && head -n 1 lib/main.dart && echo "✅ lib/main.dart present"

      # (Valfritt) Lista filer för snabb felsökning
      - name: List important paths
        run: |
          echo "---- lib ----"; ls -la lib || true
          echo "---- assets ----"; ls -la assets || true
          echo "---- assets/data ----"; ls -la assets/data || true
          echo "---- pubspec.yaml ----"; sed -n '1,200p' pubspec.yaml

      - name: Flutter pub get
        run: flutter pub get

      # Installera NDK 27 (krävs av audioplayers/path_provider)
      - name: Install Android NDK 27
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "ndk;27.0.12077973"

      # Tvinga NDK-version i projektet (både gradle.properties och ev. build.gradle)
      - name: Force NDK version
        run: |
          echo "android.ndkVersion=27.0.12077973" >> android/gradle.properties || true
          if [ -f android/app/build.gradle.kts ]; then
            grep -q 'ndkVersion' android/app/build.gradle.kts || sed -i '0,/android\s*{/{s//android {\n    ndkVersion = "27.0.12077973"/}' android/app/build.gradle.kts
          fi
          if [ -f android/app/build.gradle ]; then
            grep -q 'ndkVersion' android/app/build.gradle || sed -i '0,/android\s*{/{s//android {\n    ndkVersion "27.0.12077973"/}' android/app/build.gradle
          fi

      - name: Accept Android licenses
        run: yes | flutter doctor --android-licenses || true

      - name: Build release APK
        env:
          GRADLE_OPTS: -Dorg.gradle.jvmargs='-Xmx3g -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC'
        run: flutter build apk --release --no-tree-shake-icons

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
