name: Flutter Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Show Flutter version
        run: flutter --version

      - name: Create Android project
        run: flutter create . --platforms=android

      # (valfritt) Lista filer för att felsöka om något saknas
      - name: Debug: list files
        run: |
          ls -la
          ls -la lib || true
          ls -la assets || true
          ls -la assets/data || true

      - name: Get packages
        run: flutter pub get

      - name: Install Android NDK 27
        env:
          ANDROID_SDK_ROOT: /usr/local/lib/android/sdk
        run: |
          yes | "${ANDROID_SDK_ROOT}"/cmdline-tools/latest/bin/sdkmanager "ndk;27.0.12077973"

      - name: Set ndkVersion in Android build files
        shell: bash
        run: |
          FILE_KTS="android/app/build.gradle.kts"
          FILE_GROOVY="android/app/build.gradle"
          if [ -f "$FILE_KTS" ]; then
            grep -q 'ndkVersion' "$FILE_KTS" || sed -i '0,/android\s*{/{s//android {\n    ndkVersion = "27.0.12077973"/}' "$FILE_KTS"
          elif [ -f "$FILE_GROOVY"_]()
