name: Flutter Android (recreate android folder)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable 3.22.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      # 🔧 Viktigt: ta bort gammal android/ och skapa en ny modern
      - name: Recreate android/ with modern Gradle template
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.kalleboo --project-name guessheritage
          # Lägg till internet-tillstånd om det saknas (för att ladda bilder via nätet)
          if ! grep -q 'android.permission.INTERNET' android/app/src/main/AndroidManifest.xml; then
            sed -i '1i <uses-permission android:name="android.permission.INTERNET" />' android/app/src/main/AndroidManifest.xml
          fi

      - name: Analyze
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release --target=lib/main.dart

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
