name: "Android: Build APK"

on:
  workflow_dispatch:
    inputs:
      generate_icons:
        description: 'Generate launcher icons before build (true/false)'
        required: false
        default: 'true'
  push:
    branches: [ main ]
    paths:
      - "lib/**"
      - "assets/**"
      - "pubspec.yaml"
      - ".github/workflows/flutter-android.yml"

concurrency:
  group: android-build-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 40

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"
          channel: stable

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: |
          flutter analyze --no-fatal-infos
          echo "Flutter analysis completed"

      - name: Generate launcher icons (optional)
        if: ${{ github.event.inputs.generate_icons != 'false' }}
        run: flutter pub run flutter_launcher_icons

      - name: Build APK
        run: flutter build apk --release

      - name: Upload release APK
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
