name: Flutter Android (recreate android folder)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (stable 3.22.2)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          cache: true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      # ✅ Skapa om android/ och skriv en korrekt AndroidManifest.xml
      - name: Recreate android/ and write valid AndroidManifest.xml
        run: |
          rm -rf android
          flutter create . --platforms=android --org com.kalleboo --project-name guessheritage

          cat > android/app/src/main/AndroidManifest.xml <<'XML'
          <manifest xmlns:android="http://schemas.android.com/apk/res/android">
              <!-- Internet behövs för att ladda bilder/HTTP -->
              <uses-permission android:name="android.permission.INTERNET"/>
              <application
                  android:label="guessheritage"
                  android:name="${applicationName}"
                  android:icon="@mipmap/ic_launcher">
                  <activity
                      android:name=".MainActivity"
                      android:exported="true"
                      android:launchMode="singleTop"
                      android:theme="@style/LaunchTheme"
                      android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
                      android:hardwareAccelerated="true"
                      android:windowSoftInputMode="adjustResize">
                      <intent-filter>
                          <action android:name="android.intent.action.MAIN"/>
                          <category android:name="android.intent.category.LAUNCHER"/>
                      </intent-filter>
                  </activity>
                  <!-- NormalTheme används efter att LaunchTheme tas bort -->
                  <meta-data
                      android:name="io.flutter.embedding.android.NormalTheme"
                      android:resource="@style/NormalTheme"/>
                  <meta-data
                      android:name="flutterEmbedding"
                      android:value="2"/>
              </application>
          </manifest>
          XML

          echo "----- AndroidManifest.xml -----"
          cat android/app/src/main/AndroidManifest.xml
          echo "--------------------------------"

      - name: Analyze
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release --target=lib/main.dart

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
