name: Flutter Android (stable)

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Set up Flutter (3.22.2 stable)
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.2'
          cache: true

      # (Valfritt) Installera NDK 27 om du behöver native/ffmpeg o.dyl.
      - name: Install Android NDK 27
        run: |
          echo "y" | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --install "ndk;27.0.12077973" || true

      - name: Flutter doctor
        run: flutter doctor -v

      - name: Pub get
        run: flutter pub get

      - name: Analyze
        run: flutter analyze

      - name: Build APK
        run: flutter build apk --release --target=lib/main.dart

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-release.apk
