name: Generate launcher icons

on:
  workflow_dispatch:
  push:
    paths:
      - "pubspec.yaml"
      - "assets/icons/**"
      - ".github/workflows/generate-icons.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.22.2"   # eller "stable"

      - name: Install dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Commit generated icons
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(icons): generate launcher icons"
          branch: main
          file_pattern: |
            android/app/src/main/res/**
            pubspec.lock
