name: Generate launcher icons

on:
  workflow_dispatch:
  push:
    paths:
      - "pubspec.yaml"
      - "assets/icons/**"
      - ".github/workflows/generate-icons.yml"

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.pub-cache
            ${{ github.workspace }}/.dart_tool
          key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            flutter-${{ runner.os }}-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"   # Updated for consistency

      - name: Install dependencies
        run: flutter pub get

      - name: Generate launcher icons
        run: flutter pub run flutter_launcher_icons

      - name: Commit generated icons
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(icons): generate launcher icons"
          branch: main
          file_pattern: |
            android/app/src/main/res/**
            pubspec.lock
